baseURL = "https://cv.gangyao.me/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
googleAnalytics = "UA-187919588-1"
title = "CV | Gang Yao"
# Get last modified date for content from Git?
enableGitInfo = true

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#3f4ed4"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 2

# Enable users to switch between day and night mode?
day_night = true
