baseURL = "https://cv.gangyao.me/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
googleAnalytics = "UA-187919588"
title = "CV | Gang Yao"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#3f4ed4"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 2
